version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: DockerfileMySQL
    container_name: container-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 6283
      MYSQL_DATABASE: sre_desafio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: DockerfileApache
    container_name: container-apache
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
